tasks:
  - name: Setup Environment
    init: |
      # Install dependencies
      mvn clean install -DskipTests
    command: |
      echo "=========================================="
      echo "Selenium Java Interview Environment Ready!"
      echo "=========================================="
      echo ""
      echo "Browser View: Check port 6080 (noVNC)"
      echo "Run Tests: mvn test"
      echo "Edit: src/test/java/InterviewTest.java"
      echo ""
      echo "Waiting for commands..."

ports:
  - port: 6080
    onOpen: open-preview
    visibility: public
    description: Browser View (noVNC)
  - port: 5900
    onOpen: ignore
    description: VNC Server

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-maven

image:
  file: .gitpod.Dockerfile
